### ISSUE TITLE
Function test

### ISSUE THREAD

**Issue by XiaoyiWang98** [XiaoyiWang98/DADC#24]
Can someone perform a function test on our current features on the dev branch?

**Comment by leowhl531** [comment]
NgoHome.js --> line 18 : missing ","  ;
Both Ngo and Donor were directed to NGO home page;
Log out button on the top bar doesn't clear session,   still logged in once refresh the page.   

### **Please use our own google map api in the resource doc instead of laiOffer's especially uploading at github.**

All other features are working fine.

**Comment by XiaoyiWang98** [comment]
NgoHome.js --> line 18 : missing "," ;
Both Ngo and Donor were directed to NGO home page;
FIXED
